name: Synapse CICD
# Manual trigger with parameters
on:  
  workflow_dispatch: 
        
jobs:  
        
  Release-UAT:
    runs-on: ubuntu-latest
    steps:          
      -  run: echo "---Print Secrets---"      
      -  run: echo "CLIENTID - "${{secrets.CLIENTID}}
      -  run: echo "CLIENT SECRET - "${{secrets.CLIENTSECRET}}
      -  run: echo "subscriptionId - "${{ secrets.SUBID }}
      -  run: echo "tenantId - "${{ secrets.TENANTID }}
      
      -  run: echo "---Print Variables---"
      -  run: echo "RESOURCE_GROUP - "${{vars.RESOURCE_GROUP}}
      -  run: echo "TARGET_WORKSPACE_NAME - "${{vars.TARGET_WORKSPACE_NAME}}
        
      
          
     
